# https://www.appveyor.com/docs/lang/nodejs-iojs/
version: "{build}"

shallow_clone: true

init:
  - git config --global core.autocrlf false

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

  # https://www.appveyor.com/docs/build-configuration/#configuring-build
build: off

build_script:
  - npm run devBuild

test_script:
  - node --version && npm --version
  - npm test