# https://www.appveyor.com/docs/lang/nodejs-iojs/
version: "{build}"

shallow_clone: true

init:
  - git config --global core.autocrlf false

# Don't actually build.
build: off

environment:
  matrix:
    # node.js
    - nodejs_version: stable
    - nodejs_version: MAJOR

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
